<!DOCTYPE html>
<html>

<head>
    <title>Password Reset</title>
    <!-- meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- font -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />




    <style type="text/css">
        .pb-4 {
            padding-bottom: 1.5rem !important;
        }

        .pb-5 {
            padding-bottom: 3rem !important;
        }

        /*! Generated by Font Squirrel (https://www.fontsquirrel.com) on February 25, 2022 */



        @font-face {
            font-family: 'helveticaregular';
            src: url('{{asset("assets/mail/font/helvetica-webfont.woff2")}}') format('woff2'),
            url('{{asset("assets/mail/font/helvetica-webfont.woff")}}') format('woff');
            font-weight: normal;
            font-style: normal;

        }





        @font-face {
            font-family: 'helveticabold';
            src: url('{{asset("assets/mail/font/helvetica-bold-webfont.woff2")}}') format('woff2'),
            url('{{asset("assets/mail/font/helvetica-bold-webfont.woff")}}') format('woff');
            font-weight: normal;
            font-style: normal;

        }




        @font-face {
            font-family: 'helveticabold_oblique';
            src: url('{{asset("assets/mail/font/helvetica-boldoblique-webfont.woff2")}}') format('woff2'),
            url('{{asset("assets/mail/font/helvetica-boldoblique-webfont.woff")}}') format('woff');
            font-weight: normal;
            font-style: normal;

        }




        @font-face {
            font-family: 'helveticacompressed';
            src: url('{{asset("assets/mail/font/helvetica-compressed-5871d14b6903a-webfont.woff2")}}') format('woff2'),
            url('{{asset("assets/mail/font/helvetica-compressed-5871d14b6903a-webfont.woff")}}') format('woff');
            font-weight: normal;
            font-style: normal;

        }




        @font-face {
            font-family: 'helveticaoblique';
            src: url('{{ asset("assets/mail/font/helvetica-oblique-webfont.woff2") }}') format('woff2'),
            url('{{asset("assets/mail/font/helvetica-oblique-webfont.woff") }}') format('woff');
            font-weight: normal;
            font-style: normal;

        }




        @font-face {
            font-family: 'helveticarounded_bold';
            src: url('{{asset("assets/mail/font/helvetica-rounded-bold-5871d05ead8de-webfont.woff2") }}') format('woff2'),
            url('{{asset("assets/mail/font/helvetica-rounded-bold-5871d05ead8de-webfont.woff") }}') format('woff');
            font-weight: normal;
            font-style: normal;

        }

        /* //extneral css */











        body {
            font-family: 'helveticabold';
        }

        h1,
        h2,
        h3,
        h4,
        h5,
        h6 {
            /* //font-family: 'helveticabold'; */
            font-family: 'Google Sans';

        }

        td h1 {
            /* font-family: 'helveticabold'; */
            font-family: 'Google Sans';
        }

        td {
            font-size: 20px;
            color: #404040;
            padding-bottom: 1.5rem !important;
            /* font-family: 'Roboto,sans-serif'; */
            font-family: 'Google Sans';
        }
    </style>
</head>

<body>

    <table style="margin: 20px auto auto;width: 600px;">
        <thead>
            <tr>
                <th class="pb-3" style="text-align: left;"><img src="{{asset('assets/mail/logo.png')}}" width="225px" height="auto"></th>
            </tr>
        </thead>